language: java

jdk:
  - oraclejdk8

install: mvn install

before_install:
  # Installing Codacy code coverage reporter upload tool
  - curl -sL https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/biz.aQute.jpm/generated/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar --user init
  - ${HOME}/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  # Uploading Cobertura report to Codacy
  - ${HOME}/jpm/bin/codacy-coverage-reporter -l Java -r ./resteasy-spring-boot-starter/target/site/cobertura/coverage.xml --projectToken $CODACY_PROJECT_TOKEN