language: java
sudo: required

jdk:
  - oraclejdk8

install: mvn install

before_install:
  # Installing Codacy code coverage reporter upload tool
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >t.jar
  - sudo java -jar t.jar init
  - rm t.jar
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

after_success:
  # Uploading Cobertura report to Codacy
  - codacy-coverage-reporter -l Java -r ./resteasy-spring-boot-starter/target/site/cobertura/coverage.xml --projectToken $CODACY_PROJECT_TOKEN
  # Deploying SNAPSHOT artifacts to Maven Central
  - mvn -B -f ./resteasy-spring-boot-starter/pom.xml -s ./resteasy-spring-boot-starter/settings.xml -DskipTests=true -Dcobertura.skip deploy
